engine = "oak"
port = 7180

[[tenants]]
name = "sandbox"
rootPasswd = "demo"
key = "./.config/antbox.key"
jwk = "./.config/antbox.jwk"
storage = ["inmem/inmem_storage_provider.ts"]
repository = ["sqlite/sqlite_node_repository.ts"]
configurationRepository = ["sqlite/sqlite_configuration_repository.ts"]
eventStoreRepository = ["sqlite/sqlite_event_store_repository.ts"]
